apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}-backend-config
  labels:
    app.kubernetes.io/name: {{ include "todo.fullname" . }}-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: todo
data:
  MONGODB_URI: "{{ .Values.backend.env.MONGODB_URI }}"
