apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "todo.fullname" . }}-frontend-config
  labels:
    app.kubernetes.io/name: {{ include "todo.fullname" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/part-of: todo
data:
  NEXT_PUBLIC_API_BASE: "{{ .Values.frontend.env.NEXT_PUBLIC_API_BASE }}"
