apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "todo.fullname" . }}-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ include "todo.fullname" . }}-backend
  template:
    metadata:
      labels:
        app: {{ include "todo.fullname" . }}-backend
    spec:
      containers:
        - name: backend
          image: "{{ .Values.image.repository.backend }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 4000
          envFrom:
            - configMapRef:
                name: {{ include "todo.fullname" . }}-backend-config
          readinessProbe:
            httpGet:
              path: /tasks
              port: 4000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /tasks
              port: 4000
            initialDelaySeconds: 10
            periodSeconds: 20
          resources: {{ .Values.backend.resources | toYaml | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo.fullname" . }}-backend
  labels:
    app.kubernetes.io/name: {{ include "todo.fullname" . }}-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: {{ include "todo.fullname" . }}-backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: 4000
