{{- if .Values.mongo.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "todo.fullname" . }}-mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "todo.fullname" . }}-mongo
  template:
    metadata:
      labels:
        app: {{ include "todo.fullname" . }}-mongo
    spec:
      containers:
        - name: mongo
          image: {{ .Values.mongo.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 27017
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
spec:
  type: ClusterIP
  selector:
    app: {{ include "todo.fullname" . }}-mongo
  ports:
    - name: mongo
      port: {{ .Values.mongo.service.port }}
      targetPort: 27017
{{- end }}
