image:
  repository:
    backend: wafabenmiloud/todo-backend
    frontend: wafabenmiloud/todo-frontend
  tag: latest
  pullPolicy: IfNotPresent

mongo:
  enabled: true
  image: mongo:7.0
  auth:
    enabled: false
  service:
    port: 27017


backend:
  replicas: 1
  service:
    type: ClusterIP
    port: 4000
  env:
    MONGODB_URI: mongodb://mongo:27017/todoapp
  resources: {}

frontend:
  replicas: 1
  service:
    type: ClusterIP
    port: 3000
  env:
    NEXT_PUBLIC_API_BASE: /api
  resources: {}

ingress:
  enabled: true
  className: nginx
  host: todo.local
